export const MOVIES_START = 'MOVIES_START';
export const MOVIES_SUCCESS = 'MOVIES_SUCCESS';
export const MOVIES_FAILED = 'MOVIES_FAILED';

export const MOVIES_CHANGE_SEARCH = 'MOVIES_CHANGE_SEARCH';
export const MOVIES_CHANGE_SORT = 'MOVIES_CHANGE_SORT';
export const SORTING_MOVIES = 'SORTING_MOVIES';

export const MOVIE_START = 'MOVIE_START';
export const MOVIE_SUCCESS = 'MOVIE_SUCCESS';
export const MOVIE_FAILED = 'MOVIE_FAILED';

